In [1]:
# Import library yang diperlukan

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
# Load dataset iris
iris = load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n'

In [5]:
#dtype ndarray
x, y = iris.data, iris.target
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>

In [6]:
# Menampilkan 5 data pertama dari x dan y dalam bentuk numpy array

print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]

In [7]:
# dtype pandas DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [8]:
# Modeling dengan Scikit-learn
# Syarat Modeling: tidak ada null, tidak ada missing value, data sudah dalam bentuk matriks atau sudah berupa numerik.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [9]:
# Preprocessing data simpel sekaligus modeling dengan Scikit-learn lewat pipeline

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

# Pipeline ndarray
pipe_numpy = Pipeline([("scaler", StandardScaler()), ("classifier", LinearSVC())])

# Pipeline pandas DataFrame
pipe_pandas = Pipeline([("scaler", StandardScaler()), ("classifier", LinearSVC())])

In [36]:
# jika hendak melihat hasil dari scaling  data maka bisa menggunakan code berikut ini
scaler = StandardScaler()
scaler.fit(df)
scaled_data = scaler.transform(df)
print("Hasil scaling data dengan StandardScaler:")
print(scaled_data[:5])

# contoh scaler lain yang disediakn oleh scikit-learn yaitu MinMaxScaler
from sklearn.preprocessing import MinMaxScaler 
scaler_minmax = MinMaxScaler(feature_range=(0, 1))
scaler_minmax.fit(df)  
scaled_data_minmax = scaler_minmax.transform(df)
print("Hasil scaling data dengan MinMaxScaler:")
print(scaled_data_minmax[:5])

#contoh scaler lain yang disediakn oleh scikit-learn yaitu RobustScaler
from sklearn.preprocessing import RobustScaler
scaler_robust = RobustScaler()
scaled_data_robust = scaler_robust.fit_transform(df) # method fit dan transform bisa disatukan jika dataset yang di fit dan di transform sama.
print("Hasil scaling data dengan RobustScaler:")
print(scaled_data_robust[:5])

#contoh scaler lain yang sangat yaitu normalize l1 (least absolute deviations) / norm = "l1" berikut kodenya:
from sklearn.preprocessing import normalize
l1_normalized_data = normalize(df, norm = "l1")
print("Hasil Scaling data dengan l1")
print(l1_normalized_data[:5])

#contoh scaler lain dengan normalize l2 (least square) / norm = "l2"

from sklearn.preprocessing import normalize
l2_normalized_data = normalize(df, norm = "l2")
print('Hasil Scaling data dengan l2')
print(l2_normalized_data[:5])

Hasil scaling data dengan StandardScaler:
[[-0.90068117  1.01900435 -1.34022653 -1.3154443  -1.22474487]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443  -1.22474487]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443  -1.22474487]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443  -1.22474487]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443  -1.22474487]]
Hasil scaling data dengan MinMaxScaler:
[[0.22222222 0.625      0.06779661 0.04166667 0.        ]
 [0.16666667 0.41666667 0.06779661 0.04166667 0.        ]
 [0.11111111 0.5        0.05084746 0.04166667 0.        ]
 [0.08333333 0.45833333 0.08474576 0.04166667 0.        ]
 [0.19444444 0.66666667 0.06779661 0.04166667 0.        ]]
Hasil scaling data dengan RobustScaler:
[[-0.53846154  1.         -0.84285714 -0.73333333 -0.5       ]
 [-0.69230769  0.         -0.84285714 -0.73333333 -0.5       ]
 [-0.84615385  0.4        -0.87142857 -0.73333333 -0.5       ]
 [-0.92307692  0.2        -0.81428571 -0.73333333 -0.5       ]
 [-0.61538462  1.2        -0.84285714 -0.73333333 -0.5       ]]
Hasil Scaling data dengan l1
[[0.5        0.34313725 0.1372549  0.01960784 0.        ]
 [0.51578947 0.31578947 0.14736842 0.02105263 0.        ]
 [0.5        0.34042553 0.13829787 0.0212766  0.        ]
 [0.4893617  0.32978723 0.15957447 0.0212766  0.        ]
 [0.49019608 0.35294118 0.1372549  0.01960784 0.        ]]
Hasil Scaling data dengan l2
[[0.80377277 0.55160877 0.22064351 0.0315205  0.        ]
 [0.82813287 0.50702013 0.23660939 0.03380134 0.        ]
 [0.80533308 0.54831188 0.2227517  0.03426949 0.        ]
 [0.80003025 0.53915082 0.26087943 0.03478392 0.        ]
 [0.790965   0.5694948  0.2214702  0.0316386  0.        ]]

In [11]:
# Spliting data
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# split ndarray
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=46) 

# split pandas DataFrame
df_train, df_test = train_test_split(df, test_size=0.2, random_state=46) 

# Kenapa berbeda? Karena pada ndarray antara x sebagai data dan y sebagai target terpisah, sedangkan pada pandas DataFrame antara data dan target masih dalam satu dataframe yang sama. Sehingga pada saat spliting data, pada ndarray kita harus memisahkan antara data dan target terlebih dahulu, sedangkan pada pandas DataFrame kita bisa langsung spliting data tanpa harus memisahkan antara data dan target terlebih dahulu.

print(f'x_train: {x_train.shape}, y_train: {y_train.shape}')
print(f'x_test: {x_test.shape}, y_test: {y_test.shape}')

x_train: (120, 4), y_train: (120,)
x_test: (30, 4), y_test: (30,)

In [12]:
# Training
# Training dengan ndarray
pipe_numpy.fit(x_train, y_train)
y_pred_numpy = pipe_numpy.predict(x_test)
print('Hasil Evaluasi Model Numpy')
print(classification_report(y_test, y_pred_numpy))

Hasil Evaluasi Model Numpy
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30

In [13]:
#  Training dengan pandas DataFrame
x_train_df, y_train_df = df_train.drop('target', axis=1), df_train['target']
x_test_df, y_test_df = df_test.drop('target', axis=1), df_test['target']
pipe_pandas.fit(x_train_df, y_train_df)
y_pred_pandas = pipe_pandas.predict(x_test_df)
print('Hasil Evaluasi Model Pandas DataFrame')
print(classification_report(y_test_df, y_pred_pandas))

Hasil Evaluasi Model Pandas DataFrame
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30

In [14]:
# save model
import pickle

# Save model pipeline numpy
with open('model_numpy.pkl','wb') as model_numpy_file:
    pickle.dump(pipe_numpy, model_numpy_file)

In [15]:
# Save model pipeline pandas DataFrame
with open('model_pandas.pkl', 'wb') as model_pandas_file:
    pickle.dump(pipe_pandas, model_pandas_file)

In [16]:
# Load model pipeline numpy
with open('../models/model_numpy.pkl', 'rb') as model_numpy_file:
    loaded_numpy_model = pickle.load(model_numpy_file)

In [17]:
# coba predict
new_data = [[1,1,1,1]] # tidak bisa menggunakan vektor [1,1,1,1], harus berupa matriks [[1,1,1,1]]
loaded_numpy_model.predict(new_data) # bisa saja isi variabeel new_data diubah menjadi vektor [1,1,1,1] tapi di .predict harus ada [] contoh: loaded_numpy_model.predict([new_data]).

array([1])

In [18]:
# apa artinya array([1])? ini bisa diartikan bahwa model memprediksi bahwa data baru yang kita masukkan termasuk ke dalam kelas 1. Kelas 1 ini merujuk pada target yang ada pada dataset iris, yaitu 'versicolor'. Jadi, model memprediksi bahwa data baru yang kita masukkan termasuk ke dalam kelas 'versicolor'.
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [19]:
# load model pipeline pandas DataFrame
with open('../models/model_pandas.pkl', 'rb') as model_pandas_file:
    loaded_pandas_model = pickle.load(model_pandas_file)

In [20]:
#  coba predict dengan model pandas DataFrame
# catatan : karena model pandas DataFrame dilatih dengan data yang masih berupa DataFrame, maka saat predict juga harus menggunakan DataFrame yang tentunya memiliki kolom, tidak bisa menggunakan list atau array. Jadi, kita harus membuat DataFrame baru yang memiliki kolom yang sama dengan DataFrame yang digunakan saat training, yaitu 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'. Contoh:
new_data_df = pd.DataFrame(data=[[3,3,3,3]], columns=iris.feature_names)
new_data_df

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  3                 3                  3                 3

In [21]:
loaded_pandas_model.predict(new_data_df)

# apa artinya array([2])? ini bisa diartikan bahwa model memprediksi bahwa data baru yang kita masukkan termasuk ke dalam kelas 2. Kelas 2 ini merujuk pada target yang ada pada dataset iris, yaitu 'virginica'. Jadi, model memprediksi bahwa data baru yang kita masukkan termasuk ke dalam kelas 'virginica'.

array([2])

In [22]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [24]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000